- name: K3s master node install
  hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: Install K3s
      ansible.builtin.shell: >-
        curl -sfL https://get.k3s.io | sh -

    - name: Get node token.
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      changed_when: false
      register: node_token_output

    - name: Set node_token fact.
      ansible.builtin.set_fact:
        node_token: "{{ node_token_output.stdout_lines[0] }}"

- name: Set up Helm.
  import_playbook: helm.yaml
  tags: ['helm']
